// topic_04-Angular/src/app/components/todo-card/todo-card.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Todo } from 'src/app/interfaces/todo';
import { TodoService } from 'src/app/services/todo.service';

@Component({
  selector: 'todo-card',
  templateUrl: './todo-card.component.html',
  styleUrls: ['./todo-card.component.css'],
})
export class TodoCardComponent implements OnInit {
  @Input() currentTodo: Todo; // Sends data from the parent to the child
  @Output() displayTodo = new EventEmitter<Todo>(); // Sends data from the child to the parent

  constructor(private todoService: TodoService) {}

  ngOnInit(): void {}

  onDisplayTodo(todo: Todo) {
    this.displayTodo.emit(todo);
  }

  onDeleteTodo() {
    this.todoService
      .deleteTodo(this.currentTodo._id)
      .then((response) => response.json())
      .then((result) => console.log(result))
      .catch((err) => console.log(err));
  }
}

<div class="todo-card">
  <div class="todo-card__title">{{ currentTodo.title | uppercase }}</div>
  <div class="todo-card__date">{{ currentTodo.date | date: "fullDate" }}</div>
  <div class="todo-card__description">
    {{ currentTodo.description | shorten: 10 }}
  </div>
  <progress max="100" [value]="currentTodo.progress"></progress>
  <div class="todo-card__actions">
    <button
      type="button"
      (click)="onDisplayTodo(currentTodo)"
      class="btn btn-primary"
    >
      Display
    </button>
    <button (click)="onDeleteTodo()" type="button" class="btn btn-danger">
      Delete
    </button>
  </div>
</div>

// topic_05-React/src/components/TodoCard/TodoCard.jsx
import "./TodoCard.css";
import Card from "../Card/Card";

const TodoCard = (props) => {
    console.log(props);
  return (
    <li>
      <Card className="todo-card">
        <div className="todo-card__details">
          <div className="todo-card__title">{props.title}</div>
          <div className="todo-card__content">
            <div className="todo-card__progress">
              {props.progress.toFixed(2)}%
            </div>
            <div className="todo-card__date">{props.date}</div>
            <div className="todo-card__description">{props.description}</div>
          </div>
          <div className="todo-card__actions">
            <button className="btn-danger">Delete Todo</button>
          </div>
        </div>
      </Card>
    </li>
  );
};

export default TodoCard;
