// topic_04-Angular/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  
  // header.component.html is also a class, and a child of HeaderComponent
  public headerBrandTitle: string = 'Todo Tracker';

  constructor() { }

  ngOnInit(): void {
  }
}

<header class="header">
  <div class="container__toolbar">
    <div class="header__brand">{{ headerBrandTitle }}</div>
    <div class="btn-container">
      <button class="btn btn-primary btn-header">Login</button>
      <button class="btn btn-danger btn-header">Register</button>
    </div>
    <button class="btn btn-danger btn-header">Logout</button>
  </div>
  <nav class="header__nav">
    <div class="header__nav-item">Add Todo</div>
    <div class="header__nav-item">Todo's List</div>
  </nav>
</header>

// topic_05-React/src/components/Header/Header.jsx
import "./Header.css";

const Header = () => {
  return (
    <header className="header">
      <div className="header__brand">Todo App</div>
      <nav className="header__nav">
        <a href="/" className="header__nav-item">
          Add Todo
        </a>
        <a href="/" className="header__nav-item">
          Todo Panel
        </a>
      </nav>
    </header>
  );
};

export default Header;
