// topic_05-React/src/pages/NewTodo/NewTodo.jsx
import React, { useState } from "react";
import "./NewTodo.css";

const NewTodo = () => {
  const [enteredTitle, setEnteredTitle] = useState("");
  const [enteredDate, setEnteredDate] = useState("");
  const [enteredDescription, setEnteredDescription] = useState("");

  const titleChangeHandler = (e) => {
    setEnteredTitle(e.target.value);
  };
  const dateChangeHandler = (e) => {
    setEnteredDate(e.target.value);
  };
  const descriptionChangeHandler = (e) => {
    setEnteredDescription(e.target.value);
  };

  const submitHandler = async (e) => {
    e.preventDefault();
    console.log(enteredTitle);
    console.log(enteredDate);
    console.log(enteredDescription);
  };

  return (
    <form className="form" onSubmit={submitHandler}>
      <div className="form-group">
        <label htmlFor="title" className="form-label">
          Title
        </label>
        <input
          type="text"
          className="form-input"
          id="title"
          autoComplete="off"
          onChange={titleChangeHandler}
        />
      </div>
      <div className="form-group">
        <label htmlFor="date" className="form-label">
          Date
        </label>
        <input
          type="date"
          className="form-input"
          id="date"
          autoComplete="off"
          onChange={dateChangeHandler}
        />
      </div>
      <div className="form-group">
        <label htmlFor="description" className="form-label">
          Description
        </label>
        <textarea
          id="description"
          cols="30"
          rows="10"
          className="form-input"
          onChange={descriptionChangeHandler}
        ></textarea>
      </div>
      <button className="btn-primary max-width" type="submit">
        Add Todo
      </button>
    </form>
  );
};

export default NewTodo;

// topic_04-Angular/src/app/components/new-todo/new-todo.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoService } from 'src/app/services/todo.service';

@Component({
  selector: 'new-todo',
  templateUrl: './new-todo.component.html',
  styleUrls: ['./new-todo.component.css']
})
export class NewTodoComponent implements OnInit {

  constructor(private todoService: TodoService) { }

  ngOnInit(): void {

  }

  onSubmitTodo() {
    this.todoService.createNewTodo()
    .then((response) => response.json())
    .then((result) => console.log(result));
  }
}

<div class="card">
  <form>
    <div class="control-group">
      <label for="title" class="control-label">Title</label>
      <input type="text" class="control-input" id="title" autocomplete="off" />
    </div>
    <div class="control-group">
      <label for="description" class="control-label">Description</label>
      <textarea
        appTextareaAutosize
        id="description"
        autocomplete="off"
      ></textarea>
    </div>
    <button class="btn btn-primary" type="button" (click)="onSubmitTodo()">Submit</button>
  </form>
</div>
